<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>MasterMind.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="MasterMind.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Interfaces\Interfaces.csproj" />
    <ProjectReference Include="..\..\ViewModel\ViewModel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.6.0-preview3.19128.7" />
  </ItemGroup>
</Project>